# Generated by Django 4.2.4 on 2023-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_alter_userdetails_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
