# Generated by Django 4.2.4 on 2023-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0007_remove_userdetails_bio_userdetails_birthday_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
