# Generated by Django 4.2.4 on 2023-09-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0008_alter_userpost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
