# Generated by Django 4.2.4 on 2023-09-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0009_userdetails_bio_alter_userpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='resume',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=''),
        ),
    ]
