# Generated by Django 4.2.4 on 2023-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0012_alter_userdetails_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resumes/'),
        ),
    ]
