# Generated by Django 4.2.4 on 2023-09-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0013_alter_userdetails_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='resume',
        ),
    ]
