# Generated by Django 4.2.4 on 2023-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_comment_name_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
