# Generated by Django 4.2.4 on 2023-09-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_userdetails_bio_alter_userdetails_profile_image_and_more'),
        ('forum', '0007_alter_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_details.userdetails'),
        ),
        migrations.AddField(
            model_name='forum',
            name='creator_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_details.userdetails'),
        ),
    ]
