# Generated by Django 4.2.4 on 2023-09-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_category_slug_alter_forum_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='image_url',
        ),
    ]
