# Generated by Django 4.2.4 on 2023-09-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagedetails',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
